// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title Groth16 Verifier Interface / Mock
 * @notice In production, this file will be generated by snarkjs from the prove/verify key.
 * This mockup mirrors the standard Groth16 verifyProof signature.
 */
contract Verifier {
    /**
     * @notice Verify a Groth16 proof.
     * @param a Proof parameters a
     * @param b Proof parameters b
     * @param c Proof parameters c
     * @param input Public inputs: [merkleRoot, nullifierHash]
     * @return r True if verification is successful, false otherwise.
     */
    function verifyProof(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[2] calldata input
    ) public view returns (bool r) {
        // Mock verification logic for setup. Returns true.
        // During compilation and deployment, this acts as the interface.
        // Standard SnarkJS compiled verifier will replace this contract in production.
        return true;
    }
}
